source: docs
# To exclude inside docs/
exclude:
  - assets/scripts
  - assets/styles
  - assets/graphics/collecticons
baseurl: https://docs.openaerialmap.org
kramdown:
  input: GFM
  syntax_highlighter: rouge
