source: docs
# To exclude inside docs/
exclude:
  - assets/scripts
  - assets/styles
  - assets/graphics/collecticons
baseurl: http://hotosm.github.io/oam-docs
kramdown:
  input: GFM
  syntax_highlighter: rouge